### ISSUE TITLE
Add google analytics 

### ISSUE THREAD

**Issue by biparnakroy** [ieee-ju/IEEE-New#23]
@ayan-biswas0412

**Comment by ayan-biswas0412** [comment]
![image](https://user-images.githubusercontent.com/52851184/92023989-2d00aa00-ed7b-11ea-91a4-2cf46067fa6e.png)

@biparnakroy working fine 

Check at google analytics console -- if everything fine close the issue
FYI @preeti98 @rohan-mitra
